// Auto-generated by tools/w4a8_block_rtl_export.py. Do not edit by hand.
// Per-stage right shifts + dimension constants for w4a8_block_ctrl.

localparam integer BC_HIDDEN       = 128;
localparam integer BC_HEAD_DIM     = 128;
localparam integer BC_LOG2_HIDDEN  = 7;
localparam integer BC_LOG2_HEAD    = 7;
localparam integer BC_GAMMA_LOG2   = 6;
localparam integer BC_EXP_LUT_LEN  = 17;

localparam integer BC_S_LN1_OUT    = 0;
localparam integer BC_S_Q_REQUANT  = 1;
localparam integer BC_S_K_REQUANT  = 1;
localparam integer BC_S_V_REQUANT  = 0;
localparam integer BC_S_SCORES     = 12;
localparam integer BC_S_ATTN_OUT   = 0;
localparam integer BC_S_LIFT       = 0;
localparam integer BC_S_LN2_OUT    = 1;
localparam integer BC_S_FFN_UP_OUT = 0;
localparam integer BC_S_BLK_TRIM   = 0;
