#!/usr/bin/env python3
"""Emit RTL-side artifacts for the Step 4 W4A8 block engine.

Reuses the bit-exact Python golden in ``w4a8_block_full.py`` and writes:

  1. bram_init/*.hex          $readmemh constant tables (gamma/beta/lut/kv)
  2. w4a8_block_consts.vh      shift localparams for the RTL
  3. test_vectors/w4a8_block/  hidden_in, block_out_golden, and per-stage
                               intermediates for tb_w4a8_block.v assertions

Every value comes from the SAME golden computation the firmware header and
host-C blob use, so the RTL block engine has an exact target to match.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Sequence

from w4a8_block_full import (
    EXP_LUT_LEN,
    GAMMA_LOG2,
    HEAD_DIM,
    HIDDEN,
    LOG2_HEAD,
    LOG2_HIDDEN,
    build_exp_lut,
    build_fixed_inputs,
    build_gelu_lut,
    load_block_params,
    run_full_block_py,
)

REPO = Path(__file__).resolve().parent.parent
BRAM_INIT = REPO / "fpga" / "bram_init"
RTL_NEW = REPO / "fpga" / "trans" / "trans.srcs" / "sources_1" / "new"
TV_DIR = REPO / "fpga" / "test_vectors" / "w4a8_block"


def _hex_line(value: int, bits: int) -> str:
    """Two's-complement hex with ceil(bits/4) digits (matches $readmemh)."""
    mask = (1 << bits) - 1
    digits = (bits + 3) // 4
    return f"{value & mask:0{digits}x}"


def write_hex(path: Path, values: Sequence[int], bits: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="ascii", newline="\n") as f:
        for v in values:
            f.write(_hex_line(int(v), bits) + "\n")


def emit_bram_init(lns: dict, inputs: dict) -> None:
    ln1_g, ln1_b = lns["ln1"]
    ln2_g, ln2_b = lns["ln2"]
    write_hex(BRAM_INIT / "ln1_gamma.hex", ln1_g, 8)
    write_hex(BRAM_INIT / "ln1_beta.hex", ln1_b, 16)
    write_hex(BRAM_INIT / "ln2_gamma.hex", ln2_g, 8)
    write_hex(BRAM_INIT / "ln2_beta.hex", ln2_b, 16)
    write_hex(BRAM_INIT / "gelu_lut.hex", lns["gelu_lut"], 8)
    write_hex(BRAM_INIT / "exp_lut.hex", lns["exp_lut"], 16)
    write_hex(BRAM_INIT / "kv_prev_k.hex", inputs["kv_prev_k"], 8)
    write_hex(BRAM_INIT / "kv_prev_v.hex", inputs["kv_prev_v"], 8)


def emit_consts_vh(shifts: dict, path: Path) -> None:
    s = shifts
    lines = [
        "// Auto-generated by tools/w4a8_block_rtl_export.py. Do not edit by hand.",
        "// Per-stage right shifts + dimension constants for w4a8_block_ctrl.",
        "",
        f"localparam integer BC_HIDDEN       = {HIDDEN};",
        f"localparam integer BC_HEAD_DIM     = {HEAD_DIM};",
        f"localparam integer BC_LOG2_HIDDEN  = {LOG2_HIDDEN};",
        f"localparam integer BC_LOG2_HEAD    = {LOG2_HEAD};",
        f"localparam integer BC_GAMMA_LOG2   = {GAMMA_LOG2};",
        f"localparam integer BC_EXP_LUT_LEN  = {EXP_LUT_LEN};",
        "",
        f"localparam integer BC_S_LN1_OUT    = {s['S_LN1_OUT']};",
        f"localparam integer BC_S_Q_REQUANT  = {s['S_Q_REQUANT']};",
        f"localparam integer BC_S_K_REQUANT  = {s['S_K_REQUANT']};",
        f"localparam integer BC_S_V_REQUANT  = {s['S_V_REQUANT']};",
        f"localparam integer BC_S_SCORES     = {s['S_SCORES']};",
        f"localparam integer BC_S_ATTN_OUT   = {s['S_ATTN_OUT']};",
        f"localparam integer BC_S_LIFT       = {s['S_LIFT']};",
        f"localparam integer BC_S_LN2_OUT    = {s['S_LN2_OUT']};",
        f"localparam integer BC_S_FFN_UP_OUT = {s['S_FFN_UP_OUT']};",
        f"localparam integer BC_S_BLK_TRIM   = {s['S_BLK_TRIM']};",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii", newline="\n")


def emit_tb_vectors(result: dict, inputs: dict) -> None:
    # Inputs / outputs
    write_hex(TV_DIR / "hidden_in.hex", inputs["hidden_in"], 8)
    write_hex(TV_DIR / "block_out_golden.hex", result["block_out"], 32)
    # Per-stage intermediates (bit widths chosen to match RTL scratch).
    write_hex(TV_DIR / "ln1_q8.hex", result["ln1_q8"], 8)
    write_hex(TV_DIR / "qkv_out.hex", result["qkv_out"], 32)
    write_hex(TV_DIR / "Q_q8.hex", result["Q_q8"], 8)
    write_hex(TV_DIR / "K1_q8.hex", result["K1_q8"], 8)
    write_hex(TV_DIR / "V1_q8.hex", result["V1_q8"], 8)
    write_hex(TV_DIR / "scores_q8.hex", result["scores_q8"], 8)
    write_hex(TV_DIR / "probs_q15.hex", result["probs_q15"], 16)
    write_hex(TV_DIR / "attn_q8.hex", result["attn_q8"], 8)
    write_hex(TV_DIR / "proj_out.hex", result["proj_out"], 32)
    write_hex(TV_DIR / "res1.hex", result["res1"], 32)
    write_hex(TV_DIR / "ln2_out.hex", result["ln2_out"], 32)
    write_hex(TV_DIR / "ln2_q8.hex", result["ln2_q8"], 8)
    write_hex(TV_DIR / "ffn_up_out.hex", result["ffn_up_out"], 32)
    write_hex(TV_DIR / "ffn_up_q8.hex", result["ffn_up_q8"], 8)
    write_hex(TV_DIR / "gelu_out.hex", result["gelu_out"], 8)
    write_hex(TV_DIR / "ffn_dn_out.hex", result["ffn_dn_out"], 32)
    write_hex(TV_DIR / "ln1_out.hex", result["ln1_out"], 32)


def build_all(checkpoint: Path) -> tuple[dict, dict, dict]:
    params = load_block_params(checkpoint)
    inputs = build_fixed_inputs()
    gelu_lut = build_gelu_lut()
    exp_lut = build_exp_lut()
    lns = {
        "ln1": params["ln1"],
        "ln2": params["ln2"],
        "gelu_lut": gelu_lut,
        "exp_lut": exp_lut,
    }
    result = run_full_block_py(
        inputs["hidden_in"],
        weights=params["weights"],
        ln1=params["ln1"],
        ln2=params["ln2"],
        gelu_lut=gelu_lut,
        exp_lut=exp_lut,
        kv_prev_k=inputs["kv_prev_k"],
        kv_prev_v=inputs["kv_prev_v"],
    )
    return result, inputs, lns


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--checkpoint", type=Path, default=REPO / "out" / "tiny_char_lm.pt"
    )
    args = parser.parse_args()

    result, inputs, lns = build_all(args.checkpoint)
    emit_bram_init(lns, inputs)
    emit_consts_vh(result["shifts"], RTL_NEW / "w4a8_block_consts.vh")
    emit_tb_vectors(result, inputs)

    print(f"bram_init  -> {BRAM_INIT}")
    print(f"consts.vh  -> {RTL_NEW / 'w4a8_block_consts.vh'}")
    print(f"tb vectors -> {TV_DIR}")
    print(f"block_out range = [{min(result['block_out'])}, {max(result['block_out'])}]")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
