#!/usr/bin/env python3
"""Export row-major INT4 weights + scales + act + y_ref for CPU W4A8 baseline.

The FPGA engine consumes weights in a 16-bank packed layout; a CPU GEMV would
have to undo the bank permutation on every load. To get a clean CPU baseline
that measures pure compute (not bank-shuffle overhead), this script emits the
same per-layer weights in a CPU-natural row-major INT4 layout:

  - W_q is M rows of N signed INT4 values
  - byte b of row r packs:
        low nibble  = W_q[r][2*b]
        high nibble = W_q[r][2*b + 1]

Activations and y_ref are exported as plain int8 / int32 arrays. Activations
are generated by reusing build_vectors(seed=1), so a CPU run sees the same x
that the on-board FPGA self-test sees and CPU y must match FPGA y bit-exactly.

Default representative layers (chosen for Step 2 speedup report):
  - layer0_proj  (128x128)  -- square, common
  - layer0_qkv   (384x128)  -- tall, exposes engine throughput
  - lm_head      (64x128)   -- short, exposes call overhead
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

sys.path.insert(0, str(Path(__file__).resolve().parent))
from w4a8_common import DEFAULT_SHIFT, golden_linear  # noqa: E402
from w4a8_engine_vectors import (  # noqa: E402
    TARGET_CONFIG,
    _checkpoint_layers,
    build_vectors,
)

DEFAULT_REP_LAYERS = ("layer0_proj", "layer0_qkv", "lm_head")


def pack_int4_row_major(W_q: Sequence[Sequence[int]]) -> list[int]:
    """Pack signed INT4 matrix into a flat byte stream, row-major.

    Byte index = r * (N // 2) + (c // 2). Low nibble = W_q[r][2*b],
    high nibble = W_q[r][2*b + 1]. N must be even.
    """
    M = len(W_q)
    N = len(W_q[0])
    if N % 2:
        raise ValueError(f"N must be even, got {N}")
    out: list[int] = []
    for r in range(M):
        row = W_q[r]
        for b in range(N // 2):
            lo = row[2 * b] & 0xF
            hi = row[2 * b + 1] & 0xF
            out.append(lo | (hi << 4))
    return out


def unpack_int4_row_major(buf: Sequence[int], M: int, N: int) -> list[list[int]]:
    """Inverse of pack_int4_row_major, sign-extending the 4-bit values."""
    if len(buf) != M * N // 2:
        raise ValueError(f"buf length {len(buf)} != {M*N//2}")
    out: list[list[int]] = []
    for r in range(M):
        row: list[int] = []
        for b in range(N // 2):
            byte = buf[r * (N // 2) + b]
            lo = byte & 0xF
            hi = (byte >> 4) & 0xF
            row.append(lo - 16 if lo & 0x8 else lo)
            row.append(hi - 16 if hi & 0x8 else hi)
        out.append(row)
    return out


def _format_array(c_type: str, name: str, values: Sequence[int], width: int) -> list[str]:
    lines = [f"static const {c_type} {name}[{len(values)}] = {{"]
    for base in range(0, len(values), width):
        chunk = values[base:base + width]
        rendered: list[str] = []
        for value in chunk:
            if c_type == "uint8_t":
                rendered.append(f"0x{value & 0xFF:02x}")
            elif c_type == "int8_t":
                rendered.append(f"{value:4d}")
            elif c_type == "int16_t":
                rendered.append(f"{value:6d}")
            elif c_type == "int32_t":
                rendered.append(f"{value}")
            else:
                raise ValueError(f"unsupported c_type {c_type!r}")
        lines.append("    " + ", ".join(rendered) + ",")
    lines.append("};")
    return lines


def emit_header(cases: list[dict], path: Path, shift: int) -> dict:
    """Write the C header with weights/scales/act/y_ref for each rep layer."""
    lines = [
        "#ifndef W4A8_CPU_REF_WEIGHTS_H",
        "#define W4A8_CPU_REF_WEIGHTS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define W4A8_CPU_REF_N_LAYERS {len(cases)}",
        f"#define W4A8_CPU_REF_SHIFT {shift}",
        "",
        "typedef struct {",
        "    int id;            /* engine layer_id (matches BRAM descriptor) */",
        "    const char *name;",
        "    int m;",
        "    int n;",
        "    int shift;",
        "    const uint8_t *w_packed;  /* row-major, 2 INT4 per byte, low nibble first */",
        "    const int16_t *scale;     /* M entries */",
        "    const int8_t  *act;       /* N entries, INT8 */",
        "    const int32_t *y_ref;     /* M entries, golden output (also matches FPGA) */",
        "} w4a8_cpu_ref_layer_t;",
        "",
    ]
    totals = {"w_bytes": 0, "scale_bytes": 0, "act_bytes": 0, "y_bytes": 0}
    for c in cases:
        slug = c["name"].replace("-", "_")
        M, N = c["M"], c["N"]
        w_packed = pack_int4_row_major(c["W_q"])
        assert len(w_packed) == M * N // 2
        # Round-trip self-check before writing.
        roundtrip = unpack_int4_row_major(w_packed, M, N)
        assert roundtrip == c["W_q"], slug
        # CPU golden using the same primitive as the engine.
        y_check = golden_linear(c["W_q"], c["x"], c["scale_q"], shift)
        assert y_check == c["y"], slug
        totals["w_bytes"] += len(w_packed)
        totals["scale_bytes"] += 2 * M
        totals["act_bytes"] += N
        totals["y_bytes"] += 4 * M
        lines.append(f"/* {slug}: M={M}, N={N} */")
        lines.extend(_format_array("uint8_t", f"{slug}_w", w_packed, width=16))
        lines.append("")
        lines.extend(_format_array("int16_t", f"{slug}_scale", c["scale_q"], width=8))
        lines.append("")
        lines.extend(_format_array("int8_t", f"{slug}_act", c["x"], width=16))
        lines.append("")
        lines.extend(_format_array("int32_t", f"{slug}_y_ref", c["y"], width=8))
        lines.append("")
    lines.append(
        f"static const w4a8_cpu_ref_layer_t w4a8_cpu_ref_layers[W4A8_CPU_REF_N_LAYERS] = {{"
    )
    for c in cases:
        slug = c["name"].replace("-", "_")
        lines.append(
            f'    {{ {c["id"]}, "{c["name"]}", {c["M"]}, {c["N"]}, '
            f"W4A8_CPU_REF_SHIFT, {slug}_w, {slug}_scale, {slug}_act, {slug}_y_ref }},"
        )
    lines.append("};")
    lines.extend(["", "#endif", ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")
    return totals


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--checkpoint", type=Path, default=Path("out/tiny_char_lm.pt"))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("lecture2_0420_release/test1/application/w4a8_cpu_ref_weights.h"),
    )
    parser.add_argument("--seed", type=int, default=1, help="must match engine vectors seed")
    parser.add_argument(
        "--layers",
        nargs="+",
        default=list(DEFAULT_REP_LAYERS),
        help="layer names to export",
    )
    args = parser.parse_args()

    if args.checkpoint.exists():
        weights, cfg = _checkpoint_layers(args.checkpoint)
        source = f"checkpoint {args.checkpoint}"
    else:
        weights, cfg = None, TARGET_CONFIG
        source = f"synthetic (seed={args.seed})"
    vec = build_vectors(cfg, args.seed, weights)
    by_name = {c["name"]: c for c in vec["cases"]}
    missing = [n for n in args.layers if n not in by_name]
    if missing:
        raise SystemExit(f"unknown layer name(s): {missing}")
    cases = [by_name[n] for n in args.layers]

    totals = emit_header(cases, args.out, DEFAULT_SHIFT)
    print(f"source: {source}")
    print(f"layers: {[c['name'] for c in cases]}")
    for c in cases:
        print(
            f"  {c['name']:18s} M={c['M']:>3} N={c['N']:>3}  "
            f"w_bytes={c['M']*c['N']//2:>6}  "
            f"scale_bytes={c['M']*2:>4}  "
            f"act_bytes={c['N']:>3}  y_bytes={c['M']*4:>4}"
        )
    total = sum(totals.values())
    print(
        f"total: w={totals['w_bytes']}  s={totals['scale_bytes']}  "
        f"act={totals['act_bytes']}  y={totals['y_bytes']}  "
        f"sum={total} bytes ({total/1024.0:.1f} KiB)"
    )
    print(f"wrote: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
